version = 0.1
[default.deploy.parameters]
stack_name = "PedidoServiceSam"
resolve_s3 = true
s3_prefix = "PedidoServiceSam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"PedidoServiceSam\" TestFrameworkName=\"GenericE2ETestFramework\""
image_repositories = []
